version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
file_exists_behavior: OVERWRITE
